class: dmc
name: "${env.embodiment}-${env.task}"
embodiment: reacher
task: easy
supported_tasks: [easy, hard]
action_repeat: 4
sensors:
  position:
    modility: tabular
    order: first
  to_target:
    modility: tabular 
    order: first
  velocity:
    modility: tabular
    order: second
  image:
    modility: visual
    order: first